services: 
  app:
    image: trep1337/devops-for-programmers-project-lvl1
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test
    environment:
      DATABASE_HOST: $DATABASE_HOST
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_USERNAME: $DATABASE_USERNAME
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_PORT: $DATABASE_PORT
    depends_on:
      db:
        condition: service_healthy

  caddy:
    image: caddy:2.5.1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app

  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DATABASE_USERNAME -d $DATABASE_NAME" ]
      interval: 5s
      timeout: 3s
      retries: 3
