version: '3'
services: 
  app:
    image: trep1337/devops-for-programmers-project-lvl1
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test
    volumes:
      - '/app/'
    depends_on:
      - db

  caddy:
    image: caddy:2.5.1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_HOST=${DATABASE_HOST}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRESQL_USER=${DATABASE_USERNAME}
      - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
